version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: balances_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "5173:5173"
        networks:
            - laravel_network
        user: "admin"
        depends_on:
            - mysql

    web:
        image: nginx:latest
        container_name: balances_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    mysql:
        image: mysql:8.0
        container_name: balances_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: balances_db
            MYSQL_USER: user
            MYSQL_PASSWORD: 123123
            MYSQL_ROOT_PASSWORD: root_secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
